name: 'Auto Generate Next Release Tag by Date'
description: 'Automatically generate next release tag incrementally with year, month, day and iteration based on previous release tag.'
author: 'alexvingg'
branding:
  color: 'red'
  icon: 'tag'

inputs:
  github_token:
    description: 'Github secrets token'
    required: true
  tag_prefix:
    description: 'Prefix added to the generated release tag'
    required: false
    default: 'v'

runs:
  using: 'node20'
  main: 'dist/index.js'
