name: Pre Merge

on:
  push:
    inputs:
      expected_release_tag:
        description: Expected release tag
        required: true
        type: string

jobs:
  Pre_Merge:
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Update dependencies
        run: pnpm update

      - name: Sanity testing of the action
        id: generate_release_tag
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print output
        run: |
          echo "Expected output: ${{ inputs.expected_release_tag }}"
          echo "Actual output: ${{ steps.generate_release_tag.outputs.release_tag }}"

      - name: Fail if mismatch
        if: ${{ inputs.expected_release_tag != steps.generate_release_tag.outputs.release_tag }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Actual and expected output doesnt match')

      - name: Add status check
        uses: LouisBrunner/checks-action@v2
        if: always()
        with:
          sha: ${{ github.sha }}
          token: ${{ github.token }}
          name: Pre Merge Check
          conclusion: ${{ job.status }}
