name: Test
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  Test:
    permissions:
      contents: read
    name: OS ${{ matrix.os }} + node ${{ matrix.node }}
    strategy:
      matrix:
        node: [22]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setting up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Sanity testing of the action
        id: generate_release_tag
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Manually check release tag
        run: echo "${{ steps.generate_release_tag.outputs.release_tag }}"
